export const USER_LOGIN = 'USER_LOGIN';
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const OWNER_SIGNUP = 'OWNER_SIGNUP';
export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_ABOUT_ME = 'UPDATE_ABOUT_ME';
export const UPDATE_CONTACT_INFO = 'UPDATE_CONTACT_INFO';
export const UPDATE_CUSTOMER_BASIC_DETAILS = 'UPDATE_CUSTOMER_BASIC_DETAILS';